export const GET_MY_EXCHANGES = "GET_MY_EXCHANGES"
export const SELECT_EXCHANGE = "SELECT_EXCHANGE"
export const ADD_MY_EXCHANGE = "ADD_MY_EXCHANGE"
export const DELETE_MY_EXCHANGE = "DELETE_MY_EXCHANGE"